name: Backend test coverage

on:
  push:
  workflow_dispatch:

env:
  MIN_COVERAGE: 40

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: backend
        run: yarn

      - name: Run backend tests
        working-directory: backend
        run: yarn test-ci

      - name: Check test coverage
        working-directory: backend
        run: |
          pct=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          echo "current test coverage: $pct%  (min required: $MIN_COVERAGE%)"
          if (( pct < $MIN_COVERAGE )); then
            exit 1
          fi

      - name: Move coverage report to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/coverage
          publish_branch: gh-pages
