name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          path: base-code

      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki # wiki repository info
          path: markdown

      - name: Generate folder structure
        run: |
          cd base-code
          tree_output=$(tree -d -I "node_modules")
          cd ..

      - name: Make changes to wiki page - "Folder Structure.md"
        run: |
          echo "\`\`\`" > ./folder_structure.txt
          echo "$tree_output" >> ./folder_structure.txt
          echo "\`\`\`" >> ./folder_structure.txt
          mv ./folder_structure.txt "./markdown/Folder Structure.md"

      - name: Push changes
        run: |
          cd markdown
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated folder structure page"
          git push
