name: Update Wiki with Frontend folder structure

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Directory Structure
        run: |
          tree -x -I node_modules > directory_structure.txt

      - name: Push to Wiki Repository
        uses: actions/checkout@v2
        with:
          repository: growupanand/crm-webapp # wiki repository info
          path: wiki

      - name: Make changes to wiki page - "Folder Structure.md"
        run: |
          cd base-code
          tree_output=$(tree -d -I "node_modules")
          echo "\`\`\`" > ../folder_structure.txt
          echo "$tree_output" >> ../folder_structure.txt
          echo "\`\`\`" >> ../folder_structure.txt
          cd ..
          cat ./folder_structure.txt
          mv ./folder_structure.txt "./markdown/Folder Structure.md"

      - name: Display Wiki URL
        run: |
          cd markdown
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated folder structure page"
          git push
